wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      - 3
      2:
      - 1
      - 3
      4: 3.6.12
      5: 0.10.18
clip_ratio:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.99
lam:
  desc: null
  value: 0.97
pi_lr:
  desc: null
  value: 0.0003
target_kl:
  desc: null
  value: 0.01
vf_lr:
  desc: null
  value: 0.001
